[project]
name = "slam-dunk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.1.7",
    "django-stubs>=5.1.3",
    "mypy>=1.15.0",
    "psycopg2>=2.9.10",
    "pydantic>=2.10.6",
    "ruff>=0.11.2",
]
