version: "3"

tasks:
  lint:
    desc: Run Ruff for linting
    cmds:
      - uv run ruff check .

  typecheck:
    desc: Run Mypy for type checking
    cmds:
      - uv run mypy .

  test:
    desc: Run tests with pytest
    cmds:
      - uv run pytest

  ci:
    desc: Run all CI checks
    cmds:
      - task: lint
      - task: typecheck
      - task: test

  reset_db:
    desc: "Reset the database (drop, create, and seed)"
    cmds:
      - echo "Dropping the database if it exists..."
      - psql -U postgres -c "DROP DATABASE IF EXISTS slam_dunk_development;"
      - echo "Creating the database..."
      - psql -U postgres -c "CREATE DATABASE slam_dunk_development;"
      - echo "Migrating database..."
      - uv run python core/manage.py migrate
      - echo "Running setup_db management command to seed the database..."
      # - uv run python core/manage.py setup_db
    env:
      DATABASE_URL: postgres://postgres:password@localhost:5432

  serve:
    desc: "Run the server"
    cmds:
      - echo "Running the development server"
      - uv run python core/manage.py runserver
