name: CI

on: [push, pull_request]

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest # FIXME: Choose a specific image!

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2" # NOTE: Make sure this always matches the .python-version file!

      - name: Install uv and dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          uv pip install ruff mypy django

      - name: Run Ruff (linting)
        run: uv run ruff check .

      - name: Run Mypy (type checking)
        run: uv run mypy .
